[package]
name = "seed-encrypt"
version = "0.1.0"
edition = "2021"

[dependencies]
aes = { version = "*", features = ["zeroize"] }
anyhow = { version = "*", features = ["backtrace"] }
argon2-kdf = "*"
bip39 = { version = "*", features = ["all-languages", "zeroize"] }
clap = { version = "*", features = ["derive"] }
dialoguer = { version = "*", default-features = false, features = ["fuzzy-select", "password"] }
env_logger = "*"
humantime = "*"
libseccomp = { version = "*", optional = true }
log = "*"
rand = "*"
sha2 = "*"
zxcvbn = "*"

[features]
default = ["pledge"]
pledge = ["dep:libseccomp"]
